### Dataset Split
- 모델을 나누기 위해 데이터셋을 분류하였습니다.

In [2]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv("./dataset/train.csv")

In [6]:
train['쇼핑몰'].value_counts()

S001-00001    11226
S001-00004     6927
S001-00003     3250
S001-00002     3104
S001-00010     1844
S001-00008     1748
S001-00005      519
S001-00007      116
S001-00006       81
S001-00009       79
Name: 쇼핑몰, dtype: int64

- 가장 많은 제품을 가진 쇼핑몰 하나와 나머지 쇼핑몰에 대해 다른 모델을 학습시킵니다.

In [17]:
train1 = train[train['쇼핑몰'] == 'S001-00001']
train2 = train[train['쇼핑몰'] != 'S001-00001']

In [19]:
train1

,ID,제품,대분류,중분류,소분류,브랜드,쇼핑몰,2022-01-01,2022-01-02,2022-01-03,...,2023-04-15,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24
0,SAMPLE_00000,B002-00001-00001,B002-C001-0002,B002-C002-0007,B002-C003-0038,B002-00001,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,SAMPLE_00001,B002-00002-00001,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,S001-00001,0,0,0,...,2,0,2,0,2,2,1,0,0,0
2,SAMPLE_00002,B002-00002-00002,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,SAMPLE_00003,B002-00002-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,SAMPLE_00005,B002-00003-00001,B002-C001-0001,B002-C002-0001,B002-C003-0003,B002-00003,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28889,SAMPLE_28889,B002-03798-00046,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03798,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28890,SAMPLE_28890,B002-03799-00002,B002-C001-0003,B002-C002-0008,B002-C003-0042,B002-03799,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28891,SAMPLE_28891,B002-03799-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,S001-00001,0,0,0,...,2,4,1,0,0,0,4,0,2,0
28892,SAMPLE_28892,B002-03799-00004,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,S001-00001,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28893,SAMPLE_28893,B002-03799-00005,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-03799,S001-00001,0,0,0,...,0,0,0,1,0,1,0,1,2,0

In [21]:
train1 = train1.drop(columns=['쇼핑몰']) # train1은 같은 쇼핑몰만 포함하였기 때문에 쇼핑몰 컬럼을 삭제합니다.

In [22]:
train1.to_csv('./dataset/train1.csv')
train2.to_csv('./dataset/train2.csv')

In [26]:
pd.read_csv("./dataset/brand_keyword_cnt.csv")

,브랜드,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,...,2023-04-15,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24
0,B002-00001,0.841310,0.913830,1.450530,2.422390,1.871190,1.581080,1.232950,1.174930,1.145920,...,0.449660,0.478670,0.609220,0.406150,0.565700,0.348120,0.406150,0.261090,0.290100,0.304610
1,B002-00002,12.648680,20.278500,15.332170,12.750210,13.562510,13.707570,11.937910,15.564250,14.084710,...,8.152010,11.241650,10.008700,9.994190,8.659700,9.747600,8.035970,8.384100,8.572670,10.719460
2,B002-00003,0.333620,0.435160,0.362630,0.174060,0.217580,0.464170,0.420650,0.290100,0.377130,...,0.884820,0.565700,0.826800,0.768780,0.754270,0.667240,0.246590,0.261090,0.290100,0.420650
3,B002-00004,0.130540,0.406150,0.565700,0.957350,0.768780,0.725260,0.652740,0.609220,0.536690,...,0.232080,0.116040,0.493180,0.609220,0.522190,0.696250,0.797790,0.130540,0.188560,0.652740
4,B002-00005,1.073390,1.711630,2.016240,1.914700,1.987230,2.146790,1.682620,1.378000,1.421520,...,1.972720,2.248330,2.262830,2.596460,2.146790,1.856680,1.479540,1.232950,2.074260,3.727870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3817,B002-03818,0.232076,0.261098,0.377129,0.290105,0.145053,0.449669,0.464166,0.420648,0.420648,...,0.087024,0.319113,0.232076,0.116031,0.174061,0.232076,0.087024,0.130542,0.116031,0.232076
3818,B002-03819,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3819,B002-03820,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3820,B002-03821,6.643498,10.429420,20.974884,15.462813,19.785441,18.146316,15.709400,16.420167,21.410042,...,9.486563,10.864578,13.345011,13.243477,11.024141,19.031156,19.654885,12.576229,12.068531,12.895343
3821,B002-03822,0.899330,0.623730,1.087900,0.957350,0.797790,1.203940,0.870320,0.710760,0.580210,...,0.638230,0.696250,1.436030,1.174930,1.160420,1.102400,1.174930,1.116910,1.116910,0.957350